version: "3"

services:
  node:
    build: ./
    volumes:
      - ./prisma/database.db:/srv/app/prisma/database.db:delegated
    ports:
      - "${VIRTUAL_PORT}:3000"
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
      VIRTUAL_PORT: "${VIRTUAL_PORT}"
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
